# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Kevin Marquette
# Generated on: 3/13/2018

@{
    RootModule        = 'Format-Splat.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '9d1feb53-bee6-46e7-9916-8fb141f28a11'
    Author            = 'Kevin Marquette'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Kevin Marquette. All rights reserved.'
    Description       = 'Adds PowerShell splat formatting option to vscode'
    FunctionsToExport = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    RequiredModules   = @(
        @{Module = 'Select-AST'; ModuleVersion = '0.1.0'}
    )
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            Tags       = @('Refactor', 'VSCode')
            LicenseUri = 'https://github.com/KevinMarquette/Format-Splat/blob/master/LICENSE'
            ProjectUri = 'https://github.com/KevinMarquette/Format-Splat'
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

